@orders_api=http://localhost:3000
@payments_api=http://localhost:3001

###
GET {{orders_api}}/orders

###
POST {{orders_api}}/orders
Content-Type: application/json

{
    "client_id": 4656464,
    "price": 200
}


###
GET {{payments_api}}/payments